import burger from './Assets/burger.png'
import html from './Assets/html.png'
import css from './Assets/css.png'
import javascript from './Assets/javascript.png'
import react from './Assets/react.png'
import skill1 from './Assets/skill1.png'
import skill2 from './Assets/skill2.png'
import skill3 from './Assets/skill3.png'
import skill4 from './Assets/skill4.png'
import github from './Assets/github.png'
import mail from './Assets/mail.png'
import download from './Assets/download.png'
import arrow from './Assets/arrow.png'
import human from './Assets/human.jpg'
export { burger, human, html, css, react, javascript,skill1,skill2,skill3,skill4,arrow,mail,github,download }